/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.kacperbak.java.http.clients.playground;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void testJdkClient() {
        App classUnderTest = new App();
        assert (true);
    }
}
